### PR TITLE
Update constants.ts

### PR DESCRIPTION
**Pull request by stdye**

### CODE REVIEW

**Comment by stdye** [comment]
need to import "relative atomic mass" for parent and daughter isotopes from ./src/elements/elements.json

**Comment by stdye** [comment]
looks like /ui/elements.jsx might have some clues on how to get the relative atomic mass values from src/elements

**Comment by stdye** [comment]
This PR consolidates Geo Isotope data to one table, deletes the files for separate tables, and tidies up presentation mostly on the GeoNu tab.

Review and if okay merge

**Comment by DocOtak** [comment]
Did some cleanup of an unused import (elementary charge).

Also when you want to write an isotope like <sup>238</sup>U all of the things imported from ui/elements handle this for you, so instead of `<sup>238</sup>U` write `{U238}`

Hopefully everything looks the way it should with these smallish changes.

**Pull request merged**
