### PR TITLE
Reactor Emission Fit Data

### PR DESCRIPTION
**Pull request by DocOtak**
This work in progress PR is adding additional reactor emissionsSpectrum models to the web app. As of the creation of this pull request, only the Estienne et al (2019) extra material have been added and only the <sup>238</sup>U 450d data is being plotted on the .

On the todo list:
* create a way to switch between reactor spectra models (Huber-Mueller, Estienne, etc) at run time.
* Add the additional models with documented decisions about how to handle missing areas (mostly energies lower than IBD threshold).

### CODE REVIEW

**Comment by DocOtak** [comment]
@stdye can you review the progress so far. I'd like some feedback before I get into adding more/other reactor antineutrino models.

**Comment by stdye** [comment]
This is encouraging progress!

From a quick scan of the code it looks like:

Huber-Mueller et al. 2011 uses the parametrized fits to the isotope spectra
Estienne at al. 2019 uses the published summation data.

Rates drop when using Estienne et al. 2019 compared with Huber-Mueller as expected. I have not compared the absolute changes with an independent calculation but the relative amounts look reasonable.

Notes:

neutrinoEnergyForHM will also be used for the Kopeikin et al. 2021 data
Estienne et al. paper was published in **2019** code indicates 2018

LMK if you have any specific questions

**Comment by stdye** [comment]
FYI- _et alia_ (and others) gets shortened to _et al._ in citations

**Comment by stdye** [comment]
These files contain the spectra given in Mueller et al. 2011, Huber 2011, Kopeikin et al. 2021. They are tabulated in a format similar to the Estienne et al. 2019 spectra. Uncertainties in the values are not included.

[mueller_et_al2011.txt](https://github.com/geoneutrinos/reactors/files/7901649/mueller_et_al2011.txt)

[huber2011.txt](https://github.com/geoneutrinos/reactors/files/7901645/huber2011.txt)

[kopeikin_et_al2021.txt](https://github.com/geoneutrinos/reactors/files/7901650/kopeikin_et_al2021.txt)

**Comment by DocOtak** [comment]
The new files are super helpful.

I noticed that the Mueller model has all 4 isotopes in it. Do want an independent Mueller and also a Huber+Mueller?

All values outside the 0~2 and 8~10 will be Estienne et al. 2019 (SM2018)

**Comment by stdye** [comment]
**Default model** defines values at antineutrino energies between the data points by linear interpolation- 
**0-2 MeV** Estienne et al. summation spectra
**2-8 MeV** Huber Pu239 and Pu241 spectra; Kopeikin et al. U235 and U238 spectra
**8-10 MeV** Estienne et al. summation spectra

**Comment by stdye** [comment]
**Huber-Mueller model** defines values at antineutrino energies between the data points by linear interpolation-
**0-2 MeV** Estienne et al. summation spectra
**2-8 MeV** Huber U235, Pu239, and Pu241 spectra; Mueller et al. U238 spectrum
**8-10 MeV** Estienne et al. summation spectra

**Comment by stdye** [comment]
@DocOtak The plot of the reactor isotope emission spectra on the Input tab that is being revise still has issues:

- The conversion method (CM) data in solid lines overwrite the summation method (SM) data in dot-dash lines at E<2 and E>8 MeV. I looked without success for a way to limit the display of the CM data to 2<E<8 MeV. 
- The legend box covers some of the 238U curves

**Comment by stdye** [comment]
@DocOtak Remaining issues for this PR:

- deciding which models or model combinations users can access
- naming the models
- posting the current model on the main plot and on the spectrum stats card
- adding/fixing plots of the spectra
- what else?

**Comment by stdye** [comment]
@DocOtak Need help getting the RA model name so it can be put on the detector stats card on and the main plot. It looks like the code may not be set up yet for sharing the names. Yes?

I am guessing that src/physics/reactor-antineutrinos/index.ts

> export const reactorAntineutrinoModelReducer = (state:ReactorAntineutrinoModelApp, action:ReactorAntineutrinoModelAction) => {
>   let newModel = {...state}
>   switch(action.arg){
>     case "model":
>       newModel.modelName = action.value;
>       newModel.model = newModel[newModel.modelName]
>   }
>   return newModel;

needs some added code, which is similar to that in src/physics/neutrino-cross-section.ts 

> export const crossSectionReducer = (state: CrossSection, action: CrossSectionAction): CrossSection => {
>   const crossSection = {...state}
>   switch (action.arg){
>     case "crossSection":
>       {
>         let xs = action.value as XSNames
>         crossSection.crossSection = xs
>       }  

so that the current RAName gets set as modelName.modelName or similar to be used elsewhere

**Comment by stdye** [comment]
The next step is adding uncertainties to the IBD/ES yields and antineutrino rates.

The third column in the following spectrum files is the percent uncertainty. For Estienne et al. spectra use 5% for 235U, 239Pu, 241Pu, and 10% for 238U.

[mueller_238u_450d.txt](https://github.com/geoneutrinos/reactors/files/7967697/mueller_238u_450d.txt)
[huber_235U_log.txt](https://github.com/geoneutrinos/reactors/files/7967699/huber_235U_log.txt)
[kopeikin_238U.txt](https://github.com/geoneutrinos/reactors/files/7967702/kopeikin_238U.txt)
[kopeikin_235U.txt](https://github.com/geoneutrinos/reactors/files/7967708/kopeikin_235U.txt)

Results for the IBD/ES yields should agree with Table VI in the revised draft of the web app paper for arXiv

**Comment by DocOtak** [comment]
I don't understand what is going on in the file [huber_235U_log.txt](https://github.com/geoneutrinos/reactors/files/7967699/huber_235U_log.txt)

**Comment by stdye** [comment]
sorry... uploaded the wrong file... replaced with the correct file

**Comment by DocOtak** [comment]
Hm… still not seeing the corrected huber 235U uncertainty file. Maybe just put it in a new comment rather than correcting the existing one.

**Comment by stdye** [comment]
[huber_235U.txt](https://github.com/geoneutrinos/reactors/files/7998672/huber_235U.txt)
[huber_235U.txt](https://github.com/geoneutrinos/reactors/files/7998675/huber_235U.txt)

**Comment by stdye** [comment]
FYI- Uncertainties are entered as percent in:

src/physics/reactor-antineutrinos/data/huber2011.txt
src/physics/reactor-antineutrinos/data/kopeikin_et_al2021.txt

and uncertainties are entered as fractional (% x 100) in:

src/physics/reactor-antineutrinos/data/mueller_et_al2011.txt

**Comment by DocOtak** [comment]
Please give the uncertainties a once over before I attempt to apply them to the reactor spectra.

**Comment by stdye** [comment]
The uncertainties (from linear interpolation?) are not inconsistent with those from my calculation, which uses the nearest neighbor method. Evaluating the differences (due to using different methods and/or rounding?) in more detail requires displaying more decimal places; The hover-over feature is only active on the central value.

**Comment by stdye** [comment]
Results look reasonable!

To facilitate more checks and finish up the PR, apply reactor uncertainties to Custom Cores where the fission fractions can be adjusted to 100% for one isotope.

If Custom Cores are present, then 
dR_total = sqrt[(dR_reac + dR_custom)^2 +  dR_geo^2]- reactor rate uncertainties are correlated across cores but not correlated with the geo-neutrino rate uncertainty. For dR_geo see Issue #366 .

The geo-reactor is arguably sufficiently different from the man-made cores to warrant a separate treatment of uncertainties. Indeed, its contributions to the rate should probably be listed separately. This can be addressed in a separate Issue/PR.

**Comment by stdye** [comment]
Uncertainty of closest custom core looks okay. Go ahead and pass it the total rate from custom cores- R_custom

Uncertainties from multiple custom cores add linearly (e.g. dR_custom = dR_custom_1 + dR_custom_2 + ... + dR_custom_n)

**Comment by stdye** [comment]
Looks good!

Add R_geo uncertainty - dR_geo (see Issue #366 - equations 1-3)

Then propagate dR_reac, dR_custom, dR_geo to R_total- (issue #36 equation 4)

**Comment by stdye** [comment]
Output Calculator needs to import model uncertainties for reactor antineutrinos and geo-neutrinos to replace the values currently hard coded in output-calculator.jsx

**Comment by stdye** [comment]
Output-calculator incorrectly sets deltaGeoNIU at 25% of (geoCrustNIU + geoMantleNIU)

Change deltaGeoNIU to sqrt[(deltaCrust x geoCrustNIU)^2 + (deltaMantle x geoMantleNIU^2)], which is how we calculate this uncertainty on the Detector Stats page

As we refine/change the GeoNu model we will be assigning different uncertainties to the crust and mantle contributions and separately for each of the isotopes (e.g. 232Th)

As suggested in Issue #366 these uncertainties could be set/adjusted on the GeoNu tab

**Comment by DocOtak** [comment]
Currently working on changes to integrate the geo uncertainties into the actual geo model rather than just where things are displayed.

**Comment by DocOtak** [comment]
What more is needed to finalize this? Thoughts:

* UI to modify geo uncertainties they are a "real" model now and all isotopes for both our layers can be edited
* Solar isn't used in the output calculator at all currently

**Comment by stdye** [comment]
When finished, this PR closes Issue #354 , Issue #356 , Issue #362 , Issue #366 , Issue #370 

A small additional effort (no UI required) fixes the 8B solar rates- Issue #347 and Issue #369

**Comment by stdye** [comment]
add uncertainties to geo-neutrino rates on output download

**Comment by stdye** [comment]
found a bug... systematic uncertainty of background on the output calculator is fixed; It does not change with changes to the detection efficiency function parameters

**Comment by stdye** [comment]
There looks to be legacy code in output-calculator.jsx for the old reactor model using the parametrized fits from Huber and Mueller and the estimated uncertainties of 6% above IBD threshold and 30% below IBD threshold.

**Comment by stdye** [comment]
**Add uncertainties to the downloaded spectrum and update the definition of energy binning- see **reactors-corelist.jsx**

1) Uncertainties are missing on the individual core spectrum download

2) Also it looks like energy binning is set using the old hardcoded way rather than the new universal way

3) While fixing this file, why not upgrade the controls for setting core power(>100%) and for using custom fission fractions to facilitate burn-up studies ???

**Comment by stdye** [comment]
Go ahead with the merge

**Pull request merged**
