### PR TITLE
Fix not using the bin center for oscillation functions

### PR DESCRIPTION
**Pull request by DocOtak**

### CODE REVIEW

**Comment by stdye** [comment]
I used 2018 LFs for my signal comparison. I expect this brings things into better alignment.

**Comment by DocOtak** [comment]
Does it get rid of the wiggles?

**Comment by stdye** [comment]
[signal_ratio.pdf](https://github.com/geoneutrinos/reactors/files/5839815/signal_ratio.pdf)

Not completely but they are definitely smaller now.

**Comment by stdye** [comment]
Not sure what's up with the Boulby curve at high neutrino energy. Your thoughts?

**Pull request merged**
