### PR TITLE
fix x-axis value ranges, add Plotly filenames- reactors plots

### PR DESCRIPTION
**Pull request by stdye**
The Core Direction Plot with 0 (1) core on displays cos(theta) values from 0 to 6 (2) but cos(theta)>1 is not possible. The cos(theta) range on the plot needs to be fixed to only display values [-1,1].

Above taken from comment on Issue #98

If this works, then will do the same for main spectrum plot

### CODE REVIEW

**Comment by stdye** [comment]
This looks like it works.

Try "Turn off alll cores" and look at "Core Directions w.r.t..." plot on Reactors tab- cos(theta) on x-axis now always -1 to 1

Please merge if OK

**Comment by stdye** [comment]
Aha, there is a small problem. The symbol (dot) for the core at cos(theta) = 1 gets cut in half. Maybe set max vale to 1.05?

**Comment by stdye** [comment]
looks good now on the screen and on the downloaded .png

merge 'em

**Comment by stdye** [comment]
Hmm... Filename changed from 'Unknown.png' to 'newplot-1.png' but not to 'Core-Directions'

Is "config" getting passed?

**Comment by DocOtak** [comment]
Config isn't being passed into this one... add a `config={config}` to the `<Plot>`

**Comment by stdye** [comment]
If they look OK, this PR plus #259, #260, #261 can be merged to retire issues #98 and #230

The main spectrum plot does config directly not as a variable- naming the Plot download filename will done in a separate PR

**Pull request merged**
