### PR TITLE
add ES neutrino total cross section plot

### PR DESCRIPTION
**Pull request by stdye**

### CODE REVIEW

**Comment by stdye** [comment]
Haha... this crashes the site!

**Comment by DocOtak** [comment]
Thanks to my spelling errors!

Caution! In the current architecture, the web app assumes that all functions in XSNames applies _exclusively_ to antineutrinos and not neutrinos.

**Comment by DocOtak** [comment]
"crossSectionElectionNeutrinoES" rather than electron...

**Comment by stdye** [comment]
this attempted workaround still crashes the SolarNu tab

**Comment by DocOtak** [comment]
Looks like you have ventured into fighting the type system. This will be really tricky to get right without tooling.

Is the purpose of this PR to only plot the (non anti) neutrino cross sections?

**Comment by stdye** [comment]
the neutrino total cross sections plotted fine in ddbb74f

BUT this version allowed ES_electron_neutrino and ES_mu/tau_neutrino cross sections to operate on the reactor and geo-neutrino fluxes

that started an attempt to separate antineutrinos and neutrinos...

**Comment by stdye** [comment]
one does find a number of comments indicating incomplete implementation of the neutrino cross sections in neutrino-cross-section

Are you planning to implement neutrino (non-antineutrino) cross sections differently than they currently are?

**Pull request closed without merging**
