### PR TITLE
Update physics-osc-params.tsx

### PR DESCRIPTION
**Pull request by stdye**

### CODE REVIEW

**Comment by DocOtak** [comment]
What are you trying to do with this one?

**Comment by DocOtak** [comment]
Ah, I see. please use the bootstrap text helper classes for this: add `className="text-right"` to all the elements (th and td) that need it: e.g. `<th className="text-right">`

**Comment by DocOtak** [comment]
You can also apply the style to the entire table by adding `className="text-right"` to the `<Table>` element at the top

**Comment by stdye** [comment]
Hey, you snuck in an edit on me. Just noticed that.

**Pull request merged**
