### PR TITLE
Update output-download.jsx

### PR DESCRIPTION
**Pull request by stdye**
Attempting to strip out GeoNu data and build separate output file for download.

Made filename prefix "Enu" more descriptive:
Enu -> AntiNu for Reactor/Geo
Enu -> SolarNu for Solar
Enu -> GeoNu for Geo (New, I hope)

It will be a miracle if this works. What the heck, I gotta try.

### CODE REVIEW

**Comment by DocOtak** [comment]
If you want to keep editing files without hitting the "merge" button. There is a "ellipsis menu" (click on the three dots) to the upper right of each file diff on the "Files Changed" tab.

**Comment by stdye** [comment]
It looks to me like this works. I downloaded and inspected several files and nothing crashed.

I will request your review.

**Comment by DocOtak** [comment]
We probably want to remove the geo columns from the reactor download button...

**Comment by stdye** [comment]
Looks good to me. You are driving. I hope another issue bites the dust...

**Pull request merged**
