### PR TITLE
Update plot.jsx

### PR DESCRIPTION
**Pull request by stdye**
Try to make the angular axis (azimuth) use the solar convention of CW from North like in the paper on arXiv.

### CODE REVIEW

**Comment by stdye** [comment]
Oops... hoping to avoid reading the whole manual, I copied what I found at this site-

https://plotly.com/javascript/polar-chart/

in the section Polar Chart Directions

**Comment by stdye** [comment]
Hmmm... maybe "angularaxis" is not recognized because "scatterplot" has not yet been declared. If this is the reason, then the problem could be fixed by distributing the "angularaxis" commands to each of the data declarations

**Comment by DocOtak** [comment]
What a fantastically unhelpful syntax error. The actual problem was a single quote `'` instead of a double quote `"` to close the string. This as the effect of causing the string to not actually be closed. I'm sure there is some logical reason it gave the error as expecting a comma somewhere, but you'd need to dig into the JS spec for that.

**Comment by DocOtak** [comment]
Before it's merged... do you want degree symbols on the tick labels?

**Comment by stdye** [comment]
Of course, degree symbols would be great! And the footnote about azimuth at the bottom right of the plot needs updating- N at 0 deg, E at 90 deg, etc.

**Comment by stdye** [comment]
Plot looks good now. Hopefully, there is no problem with this being stale. It shows merging into an old version. Several changes since this was started.

**Pull request merged**
