### PR TITLE
Update output-download.jsx

### PR DESCRIPTION
**Pull request by stdye**
Now try removing GeoNu data from "downloadData" so it only has Reactor data and remove "/Geo" from the buttonTitle

### CODE REVIEW

**Comment by stdye** [comment]
Wow, the editing the edited file takes way less time to determine if the code compiles

Apparently, none of the checks were needed.

**Comment by stdye** [comment]
How do I check though? There is no "Details" button to take me to the trial version.

**Comment by DocOtak** [comment]
This is a pull request which changes the other pull request... so it's, probably confusing. When editing an existing PR, you want to commit directly to that "branch" and not open another PR.

**Comment by stdye** [comment]
Ah. Can you check if it is okay?

**Comment by DocOtak** [comment]
Closing this in favor of working on it in #152 (which should be updated/building)

**Pull request closed without merging**
