### PR TITLE
Impliment cost theta plot

### PR DESCRIPTION
**Pull request by DocOtak**
So here is the first crack at it, naturally it needs refinements. Is it what is expected?

Since our data source has multiple cores at the same site tracked independently, often the largest signal is going to be from other cores at the same site (cos = 1)

### CODE REVIEW

**Comment by stdye** [comment]
It would be helpful to use marker colors matching the colors for the core types, like we have done on the map and the polar plot. In particular, I am trying to make sense of the cos#theta plot for SNOLAB.

**Comment by DocOtak** [comment]
Yeah I think I can make the colors happen.

Re making sense of the plot, the closest reactor complex is BRUCE which has something like 8 cores with different signals. It helps if you switch the plot to "show closest data on hover" (third icon from the right).

**Comment by stdye** [comment]
Try setting location to IMB. Perry core does not show on plot

**Comment by DocOtak** [comment]
Did a bunch of label cleanups, should be consistent now, though might need some tweaks in sigfigs.

For the PERRY core, what is the angle between the closest core and itself? PERRY is a single core reactor site....

**Comment by stdye** [comment]
Perry is the closest core at IMB

**Pull request merged**
