### PR TITLE
Update corrections.json

### PR DESCRIPTION
**Pull request by stdye**
fixes latitude and longitude for another 30 active (permanent shutdowns were ignored) cores in East Asia. Should improve signal estimates for Kamioka and Yemilab.

### CODE REVIEW

**Comment by DocOtak** [comment]
Let me know when this is "stable". I'm about to start working on adding the 2020 data will change how the reactor cores load and having things change under it will make things much harder...

**Comment by stdye** [comment]
Stable now. Add 2020!

**Comment by stdye** [comment]
Nothing yet. You must still be jet lagged. I am fixing more misplaced cores

**Comment by stdye** [comment]
This PR corrects LAT/LON of cores operational as of 2019. Elevation was not considered here. Issue #270 addresses elevation, suggesting topographic/bathymetric layer map for extracting elevations from LAT/LON referenced positions.

That's it! I am done fixing lat/lon for cores... I look forward to seeing the 2020 LF data online soon

**Comment by DocOtak** [comment]
Awesome, will get cracking on it tonight.

**Pull request merged**
