### PR TITLE
Update output-calculator.jsx

### PR DESCRIPTION
**Pull request by stdye**
Try Cloudflare build on unedited output-calculator.jsx. Only added a new line with an empty comment

### CODE REVIEW

**Comment by stdye** [comment]
So it can work... painfully slowly, however

**Comment by stdye** [comment]
so placeholder "useState" till there but options removed

**Comment by DocOtak** [comment]
"Prettier" is [something specific](https://prettier.io/)

**Comment by DocOtak** [comment]
Re set* methods, made by `useState`. The useState function returns an array that we are [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). that second element needs to go somewhere even if it isn't used (really need to just add the UI to actually allow editing).

**Pull request merged**
