### PR TITLE
add Muon tab

### PR DESCRIPTION
**Pull request by stdye**

### CODE REVIEW

**Comment by stdye** [comment]
Stuck and not sure how to fix. Problem started on Commit 17. Please point out the error(s)

**Comment by stdye** [comment]
UI alert: This draft PR needs a muon/neutron flux calculator. The user enters the overburden (km.w.e.) and the calculator returns the corresponding muon and neutron fluxes. The functions for calculating the fluxes already exist in the code; they produce the curves in the second plot.

**Comment by DocOtak** [comment]
Awesome, I'll get the calculator component added.

**Comment by stdye** [comment]
limit the allowed depths a user can enter from 1.5 - 8.0 km.w.e. so that the results from the parameterized equations are valid

**Comment by DocOtak** [comment]
@stdye not sure that you saw that I pushed some changes that added as basic calculator.

**Comment by stdye** [comment]
I saw but was waiting until you were done to comment

**Pull request merged**
