### PR TITLE
Create physics-halflives.tsx

### PR DESCRIPTION
**Pull request by stdye**

### CODE REVIEW

**Comment by stdye** [comment]
Might not have passed the values correctly.

When you make this work, put it on the GeoNu tab below the isotope spectrums plot

**Comment by stdye** [comment]
This looks good to me. Note the duplicated T_1/2 values. Merge or revise and merge at will

**Comment by stdye** [comment]
This PR does not involve any files under revision for the unified energy definition work that is just getting started.

Please note any concerns or problems at your earliest convenience.

**Comment by DocOtak** [comment]
This got merged manually in a way that github was unable to automatically recognize.

**Pull request closed without merging**
