### PR TITLE
Update neutrino-cross-section.ts

### PR DESCRIPTION
**Pull request by stdye**

### CODE REVIEW

**Comment by stdye** [comment]
Well, I finally broke the site!

The names I changed might be referenced elsewhere in the code and now they do not match up?

**Comment by stdye** [comment]
What is wrong here, sensei?

**Comment by DocOtak** [comment]
Hm... looks like the "CrossSectionPlots" was relying on the exact name, I suspect this was a hold over from when we didn't have a way to deal with the total cross sections.

**Comment by DocOtak** [comment]
Be aware that we currently have a "special case" name of `"Elastic Scattering: Neutrino"` for the solar neutrinos that is not user facing. The `XSNames` object affects the UI on the site.

**Comment by stdye** [comment]
Very good!

**Pull request merged**
