### PR TITLE
Include shutdown date in core database

### PR DESCRIPTION
**Pull request by DocOtak**
This is another work in progress PR to fix up the core database including shutdown dates. Currently it just displays if a core has been shutdown prior to "today".

### CODE REVIEW

**Comment by stdye** [comment]
Is this ready to merge? Please see last comment on Issue #201

**Comment by stdye** [comment]
How about remove the "Caution: ..." note and change the drop down option to "Use 100% LF for all active cores" ?

It is nice that the individual core override option to "Set Load to 100%" still works after the shutdown date. So users can still revive a dead core if their analysis wants it so.

**Comment by stdye** [comment]
or just merge the sucker and some PIA fledgling hack can make the minor touch-up changes

**Comment by stdye** [comment]
This looks very good to me. Unless you plan to make more changes, merge at will

**Comment by DocOtak** [comment]
Your "PIA fledgling hack" got a laugh out of me :smile:

**Pull request merged**
