### PR TITLE
Add "use as signal" checkbox for use in output calculator

### PR DESCRIPTION
**Pull request by DocOtak**
This is an early implementation/test of a way to handle #242

It probably needs a little more polish/features before merge. Please play with it and let me know if this looks like something that will address #242.

### CODE REVIEW

**Comment by stdye** [comment]
This will address #242 .

1) An option on the "Control all Cores" to clear all the checked Signal boxes would be a convenience to users

2) It would be super nice to see the selected Signal spectrum on the main plot, or maybe a new plot on the Output tab only

**Comment by stdye** [comment]
To facilitate analyses of the Signal (background) spectra, users will be asking for a download option

**Comment by DocOtak** [comment]
In playing around, it seems that a "Select all Filtered" cores might be very desirable. e.g. if I filter the core list for "BRUCE", I'll probably want to select all 8 cores at the complex as my signal....

**Comment by stdye** [comment]
Indeed, "Select all Filtered" would be desirable

**Comment by stdye** [comment]
Feel free to remove the "complex" selections I recently added to the Custom Core- Core Locations Suggestions and push it to this signal_box branch. They are a kludge but I was under a deadline to get something working.

**Comment by stdye** [comment]
Okay, Houston, we have a problem here. 

1) There is a 235U column on the GeoNu output file. Probably a legacy problem from adding 235U signal.

2) Output file title shows as "...Tminx.xMeV.csv" but T_min not active for IBD. Probably also a legacy problem from adding T_min to ES.

Otherwise, this looks good to me.

**Comment by stdye** [comment]
I suggest we remove "Tminx.xMeV" from IBD filenames until T_min is activated for IBD

**Comment by DocOtak** [comment]
For the core types change, if you type one of the core types "exactly" (case insensitive) into the reactor list filter box, it will switch to filtering on that rather than the core names.

This is a "quick" solution that will allow setting the "signal" to be all cores of a particular reactor type (e.g. PHWR -> all the CANDU cores)

**Comment by stdye** [comment]
Very nice... I only had trouble selecting MOX

**Comment by stdye** [comment]
Legacy "MeV" at end of IBD filename

**Comment by DocOtak** [comment]
The magic term "LEU_MOX" should work now (once the preview build finishes).

**Comment by stdye** [comment]
Very nice!

Small legacy issue- Reactor download filename starts with "AntiNu". It should probably be changed to start with "Reactor" or something similar

Somewhat stale (you were at sea at the time) user request that came to me by email from Slava at Livermore- He liked both reactor + geonu in one file. The filename for this appropriately starts with "AntiNu". I guess the button label would be "Reactor + GeoNu". He complained that he needed to change his code for reading the files. I am sure he has done this by now so there is really no need to (re)make another download. Just an FYI b/c it relates to the "AntiNu" legacy above

**Comment by DocOtak** [comment]
Merge time? Probably also send some updated instructions to the collaboration?

**Comment by stdye** [comment]
I am not sure that all the signal events (S) are showing in the output-calculator.

I set Detector at SNOLab and filter-selected PWR (330 cores) and set efficiency params to 100%. The signal events (S) came to less than 12 but the rate curve on the plot looked to have an average of about 10 /MeV over a 5 MeV range. I was guessing that there would be maybe 40 or 50 signal events

**Comment by stdye** [comment]
My stupid. I forgot to change the Signal (background) option from Closest (geoNu + other reactors)

**Comment by stdye** [comment]
Merge at will... I will send email to known users

**Pull request merged**
