### PR TITLE
Update reactors.csv

### PR DESCRIPTION
**Pull request by stdye**
TEST- 3 cores (BARAKAH-2, HONGYANHE-5, TIANWAN-6) newly on the grid in 2021 are added (there are 3 more cores new in 2021 not yet added).

How do you want these marked so they can be identifiable for display in a new layer on the main map? A unique shutdown date (2222-01)?

### CODE REVIEW

**Comment by stdye** [comment]
Your code is robust! It shows these 3 new cores even though they have no LF data (at least on Cloudflare).

They contribute no signal but one supposes this changes when LF data are present.

Test did not fail. Going ahead then with adding the other 6 cores as noted in Issue #398

**Comment by DocOtak** [comment]
So the behavior coded is:
* If in reactors.csv and not in the DBnnnn.csv files, it will default to all 0 LF (it will also 0 any negative LFs encountered but there is no upper bounds check).
* If in a DBnnnn.csv and not in reactors.csv, it will error and not convert.

**Comment by stdye** [comment]
new core type SHIDAO BAY-1 is 500 MWt HTGR (high-temperature gas-cooled reactor).

 It looks like this breaks the build. 

Either add this new type or the type can be changed to GCR in the list. What do you want to do?

Otherwise, this adds all 9 new cores reported by PRIS as new to the grid after 2020.

What are your comments on highlighting these new cores? New circle color? Note in core Pop-up? Do nothing?

**Comment by DocOtak** [comment]
We can either add it to the "databaseToKnown" mapping (src/reactor-cores/index.ts:443) or if we know power/fission fractions, we can add it as a type we know about.

**Comment by stdye** [comment]
Good point about the fission fractions, which will surely be different that those for the GCR cores. The new HTGR core type can still use the GCR gold color circle.

**Comment by stdye** [comment]
Something else is not correct. HTGR still breaks the build

**Comment by DocOtak** [comment]
The mapping is database (e.g. reactors.csv) to known where "known" is one of the POWER_FRACTIONS or FISSION_FRACTIONS keys (lines 32 to 114)

**Comment by stdye** [comment]
This looks acceptable to me and minimizes the amount of new code like making a new map layer. Merging?

**Pull request merged**
